### PR TITLE
Fix varargs generation

### LINKED ISSUE #44: Wrong code for methods with varargs
Code generated for Mocks of methods with varargs won't compile. Example:

```go
func (m *Interface) SomeMethod(_a0 Type1, _a1 ...Type2) error {
	ret := m.Called(_a0, _a1)

	var r0 error
	if rf, ok := ret.Get(0).(func(*Type1, ...Type2) error); ok {
		r0 = rf(_a0, _a1)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}
```

But it should be:

```go
func (m *Interface) SomeMethod(_a0 Type1, _a1 ...Type2) error {
	ret := m.Called(_a0, _a1)

	var r0 error
	if rf, ok := ret.Get(0).(func(*Type1, ...Type2) error); ok {
		r0 = rf(_a0, _a1...)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}
```

### PR DESCRIPTION
**Pull request by ryanbrainard**
This fixes https://github.com/vektra/mockery/issues/44 in this fork (will push to main fork later). It still does not work nice for the `MockOn` convenience methods because things get tricky with converting to interface arrays and it is not clear what the expected behavior should be, so leaving it as is for now.

cc: @fabiokung

### CODE REVIEW

**Comment by fabiokung** [comment]
:+1:

File: mockery/generator.go [hunk 1]
```diff
@@ -277,6 +278,15 @@ func (g *Generator) genList(list *ast.FieldList, addNames bool) ([]string, []str
 	return names, types, params
 }
 
+func (g *Generator) paramsAsArgNames(params []string) []string {
+	args := []string{}
+	r := regexp.MustCompile("(.+?) (\\.{3})?.+")
```
Comment (fabiokung) [inline mockery/generator.go:283]: the space in between the param name and the ellipsis (`...`) is optional in Go

Comment (ryanbrainard) [inline mockery/generator.go:283]: Mockery normalizes the params up above directly from the AST, so this
should be ok, but I can test it to make sure.

Comment (ryanbrainard) [inline mockery/generator.go:283]: I tried it out, and it does work, but I replaced the regex with direct use of the AST, which is how I really should have done it to begin with: https://github.com/ryanbrainard/mockery/pull/4
